#!/usr/bin/env bash
# Nginx install

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/html
echo "Holberton School" | sudo tee /var/www/html/index.nginx.debian.html
sudo service nginx restart
