#!/usr/bin/env bash
# Nginx install

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
new_string="Location rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "$new_string"
sudo service nginx start
