#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver web1 35.237.166.41:80 check\n\tserver web2 35.243.221.13 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
