#!/usr/bin/env bash
# OSI is an abstract model to describe layered communication and network design
if [ "$1" ]; then
    ping -c5 "$1"
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
