#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process

start () {
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
    }

stop () {
    kill "$(pgrep -f './manage_my_process')" &
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
    }

restart () {
    stop 0
    start 0
    echo "manage_my_process restarted"
    }
