#!/usr/bin/env bash
# Comment
pkill -f apache2
chmod 744 /etc/nginx/nginx.conf
sed -i "s/8080/80/g" /etc/nginx/sites-available/default
sudo service nginx stop
sudo -u nginx nginx
sudo service nginx start